### ISSUE TITLE
The process cannot access the file because it is being used by another process when run sam build

### ISSUE THREAD

**Issue by betimer** [aws/aws-toolkit-jetbrains#3455] opened 2023-01-20 02:35 UTC
**Describe the bug**

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
'C:\\Users\\betim\\AppData\\Local\\Temp\\tmpr4kzrh76'
```

**To reproduce**

**Expected behavior**
Success without any error (I have also tried to manually remove the temp file, but it turns out the error is consistent with each time it also generate again, so the root cause will be from `sam build` itself, and it generate the temp file

**Screenshots**
![image](https://user-images.githubusercontent.com/8111748/213605734-7e4c8901-3e11-4ec4-aadf-1828cdfbc75e.png)
**Your Environment**

- OS: Windwos 11 64bit

**Comment by rli** [comment] 2023-01-20 19:21
Closing in favor of https://github.com/aws/aws-sam-cli/issues/4595 since the issue reproduces outside of the toolkit

**Closed by rli** 2023-01-20 19:21 UTC
Labels: bug
