### ISSUE TITLE
JetBrains report

### ISSUE THREAD

**Issue by pgmstream** [aws/aws-toolkit-jetbrains#5156] opened 2024-12-03 17:10 UTC
com.intellij.diagnostic.PluginException: C:\Users\pmolloy\AppData\Local\JetBrains\GoLand2024.3\aws-static-resources\notifications.json [Plugin: aws.toolkit.core]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.nio.file.NoSuchFileException: C:\Users\pmolloy\AppData\Local\JetBrains\GoLand2024.3\aws-static-resources\notifications.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystemProvider.newInputStream(DelegatingFileSystemProvider.java:72)
	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
	at software.aws.toolkits.core.utils.PathUtilsKt.inputStream(PathUtils.kt:27)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase.getNotificationsFromFile(ProcessNotificationsBase.kt:42)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase.retrieveStartupAndEmergencyNotifications(ProcessNotificationsBase.kt:52)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase._init_$lambda$1(ProcessNotificationsBase.kt:36)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationPollingService.notifyObservers(NotificationPollingService.kt:142)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationPollingService.startPolling(NotificationPollingService.kt:65)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationServiceInitializer.execute(NotificationServiceInitializer.kt:20)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:496)
	... 6 more

**Comment by rli** [comment] 2024-12-03 17:23
dupe of https://github.com/aws/aws-toolkit-jetbrains/issues/5150

**Closed by rli** 2024-12-03 17:23 UTC
Labels: bug
