### ISSUE TITLE
Unhandled exception when fetching CloudWatch Logs (ECS)

### ISSUE THREAD

**Issue by dtopaloglou** [aws/aws-toolkit-jetbrains#2773] opened 2021-08-13 15:35 UTC
**Describe the bug**

This occurs when the toolkit tries to fetch CloudWatchLogs from ECS. 

```
Unhandled exception in [CoroutineName(CloudWatchLogStream), StandaloneCoroutine{Cancelling}@3cb75f8, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@33fbafd8[Running, pool size = 7, active threads = 3, queued tasks = 0, completed tasks = 30758]]

kotlinx.coroutines.channels.ClosedSendChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getSendException(AbstractChannel.kt:1106)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpCloseAndResumeWithSendException(AbstractChannel.kt:229)
	at kotlinx.coroutines.channels.AbstractSendChannel.access$helpCloseAndResumeWithSendException(AbstractChannel.kt:19)
	at kotlinx.coroutines.channels.AbstractSendChannel.sendSuspend(AbstractChannel.kt:219)
	at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:136)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.CloudWatchLogStream$refreshTable$1.invokeSuspend(CloudWatchLogStream.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To reproduce**
1. In the ECS dropdown > Clusters > {Name}
2. Right-click View Logs

**Expected behavior**

Logs should start populating.

**Screenshots**

<img width="1061" alt="Screen Shot 2021-08-13 at 11 29 05 AM" src="https://user-images.githubusercontent.com/5993176/129382855-c4d8bbf1-4078-402b-beb6-f0876a9ebfc9.png">

**Your Environment**
- OS: MAC BigSur v11.4
- JetBrains product: IntelliJ IDEA Ultimate
- JetBrains product version: 2021.2 
- AWS Toolkit version: 1.30-212
- SAM CLI version: 
- JVM/Python version:

**Additional context**

Though some logs do populate, at some point it stops and the exception is thrown (shown in image above). Once exception is thrown, refresh no longer works.

**Comment by abrooksv** [comment] 2021-08-23 15:16
We dont have the root cause that triggered the channel to close sadly.

We did push some fixes in 1.31 that contain a fix when the request to CloudWatch returns an empty set of logs. 

Can you upgrade and see if you are still seeing this issue? I have not seen it personally from my testing.

**Comment by dtopaloglou** [comment] 2021-08-24 18:08
@abrooksv I'll look into upgrading, thanks!

**Comment by rli** [comment] 2022-07-26 18:57
Closing since issue appears to be resolved. Please open a new issue if this is not the case.

**Closed by rli** 2022-07-26 18:57 UTC
Labels: bug
