### ISSUE TITLE
SAM deployment dialog does not open

### ISSUE THREAD

**Issue by Udith** [aws/aws-toolkit-jetbrains#3252] opened 2022-08-10 03:53 UTC
Cannot deploy an AWS SAM project by clicking on **Deploy Serverless Application** from the context menu of `template.yaml`  file.

**To reproduce**
1. Open an AWS SAM project
2. Open the context menu (by right clicking) of `template.yaml` file and select **Deploy Serverless Application**
3. Nothing happens in the first time and no error popup nor an error log on log file
4. Repeat step 2 again
5. An error popup shown with the error `kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog with modifiers "private"`
(Full stacktrace is available below)

**Expected behavior**
The serverless application deployment dialog should appear

**Your Environment**
- OS: **Mac OS (11.6.3)**
- JetBrains product: **IntelliJ IDEA Ultimate**
- JetBrains product version: **2022.2 (Build #IU-222.3345.118)**
- AWS Toolkit version: **1.48-222**
- SAM CLI version: **1.46.0**
- JVM/Python version: **17.0.3+7-b469.32 x86_64 (OpenJDK 64-Bit Server VM by JetBrains s.r.o.)**

**Full stacktrace**
```
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog with modifiers "private"
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
	at kotlin.reflect.jvm.internal.KProperty0Impl.get(KProperty0Impl.kt:35)
	at kotlin.reflect.jvm.internal.KProperty0Impl$Getter.invoke(KProperty0Impl.kt:44)
	at com.intellij.ui.layout.RowBuilderWithButtonGroupProperty.radioButton(LayoutBuilder.kt:72)
	at com.intellij.ui.layout.RowBuilderWithButtonGroupProperty.radioButton$default(LayoutBuilder.kt:71)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog$buildPanel$1$2$1.invoke(DeployServerlessApplicationDialog.kt:183)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog$buildPanel$1$2$1.invoke(DeployServerlessApplicationDialog.kt:182)
	at com.intellij.ui.layout.RowBuilder$DefaultImpls.row(Row.kt:55)
	at com.intellij.ui.layout.Row.row(Row.kt:145)
	at com.intellij.ui.layout.migLayout.MigLayoutRow.row(MigLayoutRow.kt:548)
	at com.intellij.ui.layout.LayoutBuilder.row(LayoutBuilder.kt)
	at com.intellij.ui.layout.RowBuilderWithButtonGroupProperty.row(LayoutBuilder.kt)
	at com.intellij.ui.layout.RowBuilder$DefaultImpls.row$default(Row.kt:54)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog$buildPanel$lambda-11$$inlined$buttonGroup$1.invoke(Row.kt:226)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog$buildPanel$lambda-11$$inlined$buttonGroup$1.invoke(Row.kt)
	at com.intellij.ui.layout.migLayout.MigLayoutBuilder.withButtonGroup(MigLayoutBuilder.kt:74)
	at com.intellij.ui.layout.migLayout.MigLayoutRow.withButtonGroup(MigLayoutRow.kt:108)
	at com.intellij.ui.layout.BaseBuilder$DefaultImpls.withButtonGroup(Row.kt:24)
	at com.intellij.ui.layout.Cell.withButtonGroup(Cell.kt:224)
	at com.intellij.ui.layout.LayoutBuilder.withButtonGroup(LayoutBuilder.kt)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog.buildPanel$jetbrains_core(DeployServerlessApplicationDialog.kt:567)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog.createCenterPanel(DeployServerlessApplicationDialog.kt:175)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog.createCenterPanel(DeployServerlessApplicationDialog.kt:68)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1308)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog.<init>(DeployServerlessApplicationDialog.kt:150)
	at software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog.<init>(DeployServerlessApplicationDialog.kt:68)
	at software.aws.toolkits.jetbrains.services.lambda.actions.DeployServerlessApplicationAction$actionPerformed$lambda-2$$inlined$runInEdt$default$1.run(actions.kt:62)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class software.aws.toolkits.jetbrains.services.lambda.deploy.DeployServerlessApplicationDialog with modifiers "private"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance.call(CallerImpl.kt:179)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	... 57 more
```

**Comment by manodnyab** [comment] 2022-08-10 16:57
Hello, this will be fixed with https://github.com/aws/aws-toolkit-jetbrains/pull/3233, and will be available with the next release.

**Comment by rli** [comment] 2022-08-10 16:59
dupe of #3228

**Closed by rli** 2022-08-10 16:59 UTC
Labels: bug, pending-release
