### ISSUE TITLE
java.lang.Throwable   (by clicking on plugin)

### ISSUE THREAD

**Issue by Edge4711** [aws/aws-toolkit-jetbrains#2759] opened 2021-08-09 00:29 UTC
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

![Screen Shot 2021-08-09 at 10 23 05 am](https://user-images.githubusercontent.com/33368143/128650262-c2090c8b-0f4c-40a3-8cc9-ac87f42afa05.jpg)

**Your Environment**
- OS: MacOS 11.5
- JetBrains product: PYCharm
- JetBrains product version:  2021-2
- AWS Toolkit version: 1-29-212
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment] 2021-08-09 14:49
Hi @Edge4711 
This is a duplicate of #2740 and fixed in 1.30

**Closed by abrooksv** 2021-08-09 14:49 UTC
Labels: bug
