### ISSUE TITLE
WebStorm Exception Thrown

### ISSUE THREAD

**Issue by jmiller-pwi** [aws/aws-toolkit-jetbrains#3480] opened 2023-02-10 16:12 UTC
Just installed AWS Toolkit in Webstorm and this happened. Not 100% sure how to reproduce.

```
java.lang.NullPointerException: Cannot invoke "com.intellij.notification.NotificationGroup.createNotification(String, String, com.intellij.notification.NotificationType, com.intellij.notification.NotificationListener)" because "group" is null
	at software.aws.toolkits.jetbrains.core.AwsTelemetryPrompter.runActivity(AwsTelemetryPrompter.kt:22)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.invokeSuspend(StartupManagerImpl.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by rli** [comment] 2023-02-10 17:34
dupe of #3433

**Closed by rli** 2023-02-10 17:34 UTC
Labels: bug
