### ISSUE TITLE
using source

### ISSUE THREAD

**Issue by flyinprogrammer** [aws/aws-toolkit-jetbrains#2153] opened 2020-10-20 14:16 UTC
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment] 2020-10-20 15:42
No content, I assume duplicate of #2154

**Closed by abrooksv** 2020-10-20 15:42 UTC
Labels: bug

**Comment by flyinprogrammer** [comment] 2020-10-20 15:47
correct, how does chrome work, and how did this even get auto-submitted? need more :coffee:
