### ISSUE TITLE
Plugin crash each time I start IntelliJ

### ISSUE THREAD

**Issue by andriesfc** [aws/aws-toolkit-jetbrains#5161] opened 2024-12-04 04:53 UTC
**Describe the bug**

When I open up the IDE the first time I see an error dialog.

**To reproduce**
1. Start IDE

**Expected behavior**
Expected to see the IDE without an error dialog.

**Your Environment**
- OS: Mac OS
- JetBrains product: IntelliJ Ultimate
- JetBrains product version: 2024.3
- AWS Core Plugin version: 3.43-24.3

### Stacktrace

```
com.intellij.diagnostic.PluginException: /Users/andriesfc/Library/Caches/JetBrains/IntelliJIdea2024.3/aws-static-resources/notifications.json [Plugin: aws.toolkit.core]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.nio.file.NoSuchFileException: /Users/andriesfc/Library/Caches/JetBrains/IntelliJIdea2024.3/aws-static-resources/notifications.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
	at software.aws.toolkits.core.utils.PathUtilsKt.inputStream(PathUtils.kt:27)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase.getNotificationsFromFile(ProcessNotificationsBase.kt:42)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase.retrieveStartupAndEmergencyNotifications(ProcessNotificationsBase.kt:52)
	at software.aws.toolkits.jetbrains.core.notifications.ProcessNotificationsBase._init_$lambda$1(ProcessNotificationsBase.kt:36)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationPollingService.notifyObservers(NotificationPollingService.kt:142)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationPollingService.startPolling(NotificationPollingService.kt:65)
	at software.aws.toolkits.jetbrains.core.notifications.NotificationServiceInitializer.execute(NotificationServiceInitializer.kt:20)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:496)
	... 6 more

```

**Comment by rli** [comment] 2024-12-09 22:43
Dupe of https://github.com/aws/aws-toolkit-jetbrains/issues/5150
Fix released in v3.44

**Closed by rli** 2024-12-09 22:43 UTC
Labels: bug
