### ISSUE TITLE
Debug run doesn't detect change in event input file until edit configuration

### ISSUE THREAD

**Issue by Marakai** [aws/aws-toolkit-jetbrains#910] opened 2019-04-12 01:28 UTC
**Describe the bug**
Debugging a function with a file-based even input does not detect changes to the JSON even file until re-opening Edit Configuration and clicking OK.

Tested with CloudFormation Create event.

**To reproduce**

1. Create function and template
2. Create an event file (instead of the preset text even samples)
3. Edit Configuration to configure
4. Click OK
5. (optional) set breakpoint early in function to be able to see even data
6. Run/Debug
7. Look at event data
8. End run/debug
9. Change JSON event file with some new/added/changed/deleted event data
10. Run/Debug
11. The event data did NOT pick up the changes!
12. End run/debug
13. Edit Configuration
14. Change nothing, simply click OK again
15. Run/Debug
16. Now the changes in the event file appear!

**Expected behavior**
Event data file should be read before every function run/debug to recognise any changes without having go through Edit Configuration/OK (unless, of course, an actual change in other configuration occurs).

**Your Environment**
 - OS: MacOS
 - JetBrains' Product: Pycharm
 - JetBrains' Product Version: 2019.1.1
 - Toolkit Version: 1.2
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: 1.8.0_201/3.7

**Comment by abrooksv** [comment] 2019-05-17 21:29
I was not able to reproduce this in 1.3

**Comment by abrooksv** [comment] 2019-05-17 21:32
Actually if you don't explicitly hit Save shortcut, it doesn't pick it up. Looks like we are missing a call to save all open documents.

**Comment by Marakai** [comment] 2019-05-18 07:03
Can confirm that doing explicit File->Save All also works (without explicit Edit Configuration step), so it does seem that save of docs is the missing step.

**Comment by abrooksv** [comment] 2019-06-11 17:16
This was fixed and released in 1.4

**Closed by abrooksv** 2019-06-11 17:16 UTC
Labels: bug
