### ISSUE TITLE
'Invalid AWS Credential' at first time to connect AWS Lambda

### ISSUE THREAD

**Issue by guayan2003** [aws/aws-toolkit-jetbrains#1275] opened 2019-10-17 05:57 UTC
Dears,

I did all installation steps (https://docs.aws.amazon.com/zh_tw/toolkit-for-jetbrains/latest/userguide/key-tasks.html#key-tasks-first-connect), but I couldn't to connect with AWS Lambda, and occurs error as below 

```
下午 12:26	Invalid AWS Credential
					Failed to switch to profile 'Profile:default'
					More info...
					Edit AWS Credential file(s)
```

Click 'More info...' and popup the message dialog and which content shown as below,
`Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

AWS CLI running as CMD as well after I running 

> $setx AWS_CA_BUNDLE "<AWS_DER_FROM_WEBSITE>

, even CMD runs AWS CLI is ok, but Intellij IDEA still cannot work normal in connecting with AWS Lambda.

I consult with AWS support, they suggest me to verify local Java AWS CA, and I did added AWS ca to my JDK1.8 and JRE1.8, and they checked is ok. (AWS CA REPO. https://www.amazontrust.com/repository/)

I also add these CA to Intellij IDEA > Setting > + AmazonRootCA1 ~ 4 and Starfield Services Root Certificate Authority, but it still cannot work. Finally, AWS support suggest me to issue the problem here.

Any one can help or adv how to solve the problem, thanks. 

> Windows 7 (Running update on 2019/10/17)
> Python version > 3.7.4
> IntelliJ IDEA > 2019.2.3
> JDK, JRE > 1.80162
>

**Comment by abrooksv** [comment] 2019-10-17 15:16
IntelliJ has its own JRE embedded inside of it (called JBRE), that is the Trust Store you would need to modify.

We currently do not respect any certs added through the Settings menu.

**Comment by guayan2003** [comment] 2019-10-18 01:24
Hi Abrooksv,

I added it on setting / tools / server certificates before, I don't know where I can configure JBRE trust store, could you please describe more, thank you.

**Comment by abrooksv** [comment] 2020-01-24 19:05
Closing as a dupe of #1009, work is being tracked there

**Closed by abrooksv** 2020-01-24 19:05 UTC
Labels: feature-request
