### ISSUE TITLE
Update Function Code - No longer works after update to Toolkit 1.18-202

### ISSUE THREAD

**Issue by cmeindl** [aws/aws-toolkit-jetbrains#2105] opened 2020-09-27 06:20 UTC
**Describe the bug**
Clicking on Update Function code from inside the AWS Explorer, the Update Code Dialog appears,  Handler is Pre Populeted.
You select a S3 Bucket from the Drop down 
I do not normally Select Build Function inside a container (But the same thing happens regardles of if selected or not)
Click Update the Button Border Turns Blue and then nothing happens, No Errors and No Progress.
Using the Deploy Serverless application (On the Yaml File) does work and all services get deployed but I use this function to update and test a single Lambda function as part of a larger app.

**To reproduce**
Using 
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 986M
Cores: 4
Non-Bundled Plugins: VisualVMLauncher, AWSCloudFormation, aws.toolkit
AWS.toolkit 1.18-202
Latest version of AWS CLI and SAM Runtime installed (Tried Re Installing)
Also uninstalled and reinstalled PLugin for IntelliJ
Currently using node.js as the base language

In AWS Explorer 
Right Click an Lambda Function  (Assumes you have previously published a lambda function with Deploy Serverless application)
Select Update Function Code
Handler should be pre Populated
Select Existing S3 Bucket (Or create new same for either)
Click Update
Nothing then happens.

**Expected behavior**
Would expect SAM Build to start and Code to be uploaded to server
**Screenshots**
![Capture](https://user-images.githubusercontent.com/11886070/94357564-3ca2b280-00dd-11eb-8c44-26e215f611c7.JPG)

**Your Environment**
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Licensed to Cameron Meindl
You have a perpetual fallback license for this version
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 986M
Cores: 4
Non-Bundled Plugins: VisualVMLauncher, AWSCloudFormation, aws.toolkit

AWS.toolkit version 1.18-202
aws-cli/2.0.52 Python/3.7.7 Windows/10 exe/AMD64
SAM CLI, version 1.3.2

![Capture](https://user-images.githubusercontent.com/11886070/94357564-3ca2b280-00dd-11eb-8c44-26e215f611c7.JPG)
**Additional context**

**Comment by hunterwerlla** [comment] 2020-09-28 16:08
I tried this out and it works, my best guess is something is throwing on the UI for some reason. @cmeindl Can your provide the portion of your IDEA.log file that maps to the time when you press "Update"? especially if there are stack traces with "software.aws" in them. To get there, press "Help -> Show Log in Explorer".

**Comment by abrooksv** [comment] 2020-09-28 21:35
I was able to reproduce this:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class software.aws.toolkits.jetbrains.services.iam.IamRole (java.lang.String is in module java.base of loader 'bootstrap'; software.aws.toolkits.jetbrains.services.iam.IamRole is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @71ae840d)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog.viewToFunctionDetails(EditFunctionDialog.kt:291)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog.upsertLambdaCode(EditFunctionDialog.kt:225)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog.access$upsertLambdaCode(EditFunctionDialog.kt:63)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog$action$4.invoke(EditFunctionDialog.kt:103)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog$action$4.invoke(EditFunctionDialog.kt:63)
	at software.aws.toolkits.jetbrains.services.lambda.upload.EditFunctionDialog$UpdateFunctionOkAction.doAction(EditFunctionDialog.kt:328)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1834)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:733)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:710)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1700)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1659)
	at software.aws.toolkits.jetbrains.services.lambda.actions.UpdateFunctionAction$actionPerformed$1$1.invoke(UpdateFunctionAction.kt:46)
	at software.aws.toolkits.jetbrains.services.lambda.actions.UpdateFunctionAction$actionPerformed$1$1.invoke(UpdateFunctionAction.kt:23)
	at software.aws.toolkits.jetbrains.utils.ResourceOperationAgainstCodePipelineKt$warnResourceOperationAgainstCodePipeline$1$$special$$inlined$runInEdt$1.run(actions.kt:67)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by abrooksv** [comment] 2020-09-28 21:47
The root cause looks to be that the resource selector combo box stays in Loading... mode when the IAM role is deleted underneath of the Lambda function.

The Update function code is the same logic as the Create/Update Lambda function configuration so a hidden UI element is breaking the Update function code dialog.

**Comment by cmeindl** [comment] 2020-09-29 07:16
Here is the Logs asscoiated with mine the only Log thrown is
2020-09-29 15:54:30,911 [70417865]   INFO - tion.HandlerCompletionProvider - Lambda handler completion provider is not registered for runtime: NODEJS. Completion is not supported. 
2020-09-29 15:54:30,932 [70417886]   INFO - tion.HandlerCompletionProvider - Lambda handler completion provider is not registered for runtime: NODEJS. Completion is not supported. 

It may not be the missing IAM role for me as when I go to update the Function configuration the IAM role correctly pre populates for the function, These functions where created via a SAM template and I do a quick publish of the code for update by the Update function process .

**Comment by abrooksv** [comment] 2020-09-30 15:40
Hmm.. Is there a red exclamation mark n the bottom right after hitting Update closing the dialog?
<img width="127" alt="Screen Shot 2020-09-30 at 8 39 46 AM" src="https://user-images.githubusercontent.com/8992246/94707671-8ca99100-02f8-11eb-8015-65f30520f141.png">

**Comment by cmeindl** [comment] 2020-10-01 11:04
> Hmm.. Is there a red exclamation mark n the bottom right after hitting Update and then closing the dialog?
> <img alt="Screen Shot 2020-09-30 at 8 39 46 AM" width="127" src="https://user-images.githubusercontent.com/8992246/94707671-8ca99100-02f8-11eb-8015-65f30520f141.png">

Nope no Red Exclamation Mark for me, I get that for other failures like when I get a failure to Load Log files (So I know what it looks like and its on my System) but this doesnt generate it.

Cam.

**Comment by abrooksv** [comment] 2020-10-01 20:10
What was the version you were using before? 1.17? 

Since we are working blind I am going through each commit that touched that dialog but so far nothing obvious

**Comment by cmeindl** [comment] 2020-10-02 09:50
> What was the version you were using before? 1.17?
> 
> Since we are working blind I am going through each commit that touched that dialog but so far nothing obvious
> 
> Also if you do Update Function Configuration, does it report any issue?

I dont have the details of the version number i was using prior,  I normally update the plugins as I get a notice for them so probably the Prior released version.  Is there a way I can manually install a prior version to test and see it if goes back to working ?


I have just done a test I opened a different project I havent used for  A while and the update function works in that project so it may be something specific to this project or its config (Although in the project that does not work i was using the update function pretty much daily)

Ill spend some time over the weekend to see if I can work out what it is about this project that makes it different.

Cam

**Comment by abrooksv** [comment] 2020-10-02 15:28
You can download old versions from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions, make sure you get the one with the suffix to match your IDE version (202 => 2020.2.x)

1.17 was the first version we supported 2020.2.x so that was probably the version you were on.

**Comment by cmeindl** [comment] 2020-10-04 11:09
> You can download old versions from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions, make sure you get the one with the suffix to match your IDE version (202 => 2020.2.x).
> 
> Download the Zip (do not extract) and on the Plugins page in the IDE, Select `Install from Disk` from the gear icon.
> 
> 1.17 was the first version we supported 2020.2.x so that was probably the version you were on.

Ive tried Going back to an older version (1.17)  and the same thing is happening , The issue also doesn't happen on a different project that I have so I suspect its Something related to this project but I cant quite figure out what it is so I think looking through changes wont be helpful ill try playing round with the project and see if I can work out what changed in the project file.

**Comment by abrooksv** [comment] 2020-10-07 15:57
Okay, let us know if you find any leads

**Comment by abrooksv** [comment] 2020-12-10 18:55
These UI implementations were overhauled in 1.21 and 1.22 so this may have corrected the issue you were seeing.

**Comment by rli** [comment] 2022-08-17 17:21
Closing due to age. Please open a new issue if this is still a problem.

**Closed by rli** 2022-08-17 17:21 UTC
Labels: bug, needs-response
