### ISSUE TITLE
Invalid Syntax in AWS Lambda Wrapper

### ISSUE THREAD

**Issue by rmagoon** [aws/aws-toolkit-jetbrains#1975] opened 2020-08-10 18:48 UTC
**Your Environment**

- OS: Ubuntu 20.04.1 LTS
- JetBrains product:PyCharm Professionsal
- JetBrains product version: 2020.2
- AWS Toolkit version: 1.17-202 AWS
- SAM CLI version: 1.18.115
- JVM/Python version: 3.8.2

**Question**

I am running a local app.lambda_handler that I have used for a project for quite a while. Recently, possibly after a PyCharm upgrade or AWS Plug upgrade I the build fails in PyCharm with the following error:

Fetching lambci/lambda:python3.8 Docker container image......
Mounting /home/rmagoon/PycharmProjects/awslambda/.aws-sam/build/Function as /var/task:ro,delegated inside runtime container
Connected to pydev debugger (build 202.6397.98)
Traceback (most recent call last):
  File "/tmp/lambci_debug_files/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/tmp/lambci_debug_files/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/var/runtime/bootstrap", line 4
    if [ -z "$AWS_LAMBDA_EXEC_WRAPPER" ]; then
            ^
SyntaxError: invalid syntax

This is when building within a container but the same error occurs when it is not used.

**Comment by abrooksv** [comment] 2020-08-10 20:56
This is caused by out of date SAM CLI and newer images I believe. Try upgrading to SAM CLI 1.0.0

**Comment by EzequielGastonOrtiz** [comment] 2020-08-11 22:01
> This is caused by out of date SAM CLI and newer images I believe. Try upgrading to SAM CLI 1.0.0

I had the same problem, installing SAM CLI again seems to solve it.

**Comment by rmagoon** [comment] 2020-08-12 11:56
Thank you. That solved the problem. I had updated everything else.
________________________________

**Comment by hunterwerlla** [comment] 2020-08-25 16:50
Closing this issue as the issue was resolved

**Closed by hunterwerlla** 2020-08-25 16:50 UTC
Labels: guidance
