### ISSUE TITLE
AWSCloudwatch log streams are not sorted correctly by the event time

### ISSUE THREAD

**Issue by aruizca** [aws/aws-toolkit-jetbrains#2765] opened 2021-08-10 10:12 UTC
**Describe the bug**
The log groups are sorted by "Last event time" but it is treating this data as a string instead of a data for sorting

**To reproduce**
Just display the log stream of any existing lambda

**Expected behavior**
The last events should be displayed first but that does not happen

**Screenshots**
<img width="1897" alt="pepr-4-confluence_–_P4CPublishingServiceStack_ts" src="https://user-images.githubusercontent.com/246477/128848975-b2fc6057-7827-4700-8741-1a29bc3dfd25.png">

**Your Environment**
- OS: MacOSx 11.5.1
- JetBrains product: Intellij IDEA
- JetBrains product version: 2021.2 Ultimate edition
- AWS Toolkit version: 1.29-212
- SAM CLI version: 1.27.2
- JVM/Python version: openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

**Comment by abrooksv** [comment] 2021-08-10 13:19
Duplicate of #2737, will be fixed in the next release

**Closed by abrooksv** 2021-08-10 13:19 UTC
Labels: bug, duplicate
