### ISSUE TITLE
Set credentials for a custom Run setting 

### ISSUE THREAD

**Issue by rogern** [aws/aws-toolkit-jetbrains#2354] opened 2021-01-20 16:07 UTC
Not sure if this is already possible or not but it would be really neat if the AWS connection setting also worked for custom run configurations. 
If you for instance have a custom program you want to run from Intellij that requires credentials because it connects to the AWS cluster.
It should provide the same access as for example `aws-okta exec` does.

---
Toolkit: AWS Toolkit For JetBrains 1.22-203
OS: Mac OS X 10.15.7
IDE: IntelliJ IDEA Ultimate Edition 2020.3

**Comment by abrooksv** [comment] 2021-01-20 16:28
Marking as a duplicate of https://github.com/aws/aws-toolkit-jetbrains/issues/926

Be aware, we are limited by what we can do. The run config has to be coded in a way to allow plugins to modify them so that we can inject the environment variables. I think our feature branch that can do this, only supports Java and Python run configs.

**Comment by abrooksv** [comment] 2021-01-20 16:29
Feature branch: https://github.com/aws/aws-toolkit-jetbrains/tree/feature/connected-execution

**Closed** 2021-01-20 16:56 UTC
Labels: duplicate
