### ISSUE TITLE
AWS Profile not showing under credentials

### ISSUE THREAD

**Issue by houayang** [aws/aws-toolkit-jetbrains#3125] opened 2022-04-14 16:44 UTC
**Describe the bug**
Credentials are seen by DataGrip, but when attempting to create a database connection, credentials do not appear under drop down option.

**To reproduce**

1. Add access key and secret to `~/.aws/credentials` or `~/.aws/config`
2. Open DataGrip and create db connection

**Expected behavior**
I should be able to select the aws profile I want to use to connect to Database.

**Screenshots**
<img width="247" alt="image" src="https://user-images.githubusercontent.com/49992271/163435076-be4fa381-4278-4fe0-9d47-06c1ce99b72e.png">

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/49992271/163435178-b809b266-7660-4896-8ccb-0d0d90c1a9f8.png">

**Your Environment**
- OS: macOS 12.3.1 w/M1 Pro
- JetBrains product: DataGrip
- JetBrains product version: 2022.1.1 (Apple Silicon)
- AWS Toolkit version: 1.42-221
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by jamierajewski** [comment] 2022-04-14 17:28
Same issue as above on macOS, only difference is Intel.

OS: macOS 12.3.1 (Intel Macbook Pro 2019)
JetBrains product: DataGrip
JetBrains product version: 2022.1.1 (Intel)
AWS Toolkit version: 1.42-221
SAM CLI version:
JVM/Python version:

**Comment by apandeycars** [comment] 2022-04-14 18:41
Experiencing the same issue as above. Also, the auto-complete isn't working. 

OS: macOS 12.3.1
JetBrains product: DataGrip
JetBrains product version: 2022.1.1 
Build #DB-221.5080.224, built on April 13, 2022
AWS Toolkit version: 1.42-221

**Comment by rli** [comment] 2022-04-19 16:52
`1.43-EAP.2022.04.19-221` is now available. We'd appreciate confirmation that the issue is now fixed in this build, otherwise `1.43` should be coming out sometime this week

**Comment by houayang** [comment] 2022-04-19 17:40
@rli verified that it is working fine for me now on EAP

**Comment by rli** [comment] 2022-04-28 20:59
1.43-221 has been released

**Closed by rli** 2022-04-28 20:59 UTC
Labels: bug, pending-release
