### ISSUE TITLE
[0.5] Bucket cannot be created in regions other than us-east-1

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#346] opened 2018-10-26 17:56 UTC
**Describe the bug**

In Upload Lambda Panel, bucket cannot be created in regions other than us-east-1. An S3 Exception pops up saying `The unspecified location constraint is incompatible for the region specific endpoint this request was sent to`.

**To reproduce**

Select the default region to us-west-2 and select a valid a credential profile. Create a local Lambda handler and upload it to AWS by clicking the gutter icon beside it. Click **Create** button in the bucket row, you will see the error in the Event Log.

**Expected behavior**

**Screenshots**

```
software.amazon.awssdk.services.s3.model.S3Exception: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. (Service: S3Client, Status Code: 400, Request ID: 14685BF4BAD5E08D)
	...
	at software.aws.toolkits.jetbrains.services.lambda.upload.UploadToLambdaController$load$5$$special$$inlined$run$lambda$1.invoke(UploadToLambdaModal.kt:172)
	at software.aws.toolkits.jetbrains.services.lambda.upload.UploadToLambdaController$load$5$$special$$inlined$run$lambda$1.invoke(UploadToLambdaModal.kt:117)
	at software.aws.toolkits.jetbrains.utils.ui.UiUtils$addAndSelectValue$1.run(UiUtils.kt:39)
	...
```

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:

**Additional context**

**Comment by abrooksv** [comment] 2018-10-26 19:11
Caused by the SDK not adding in the interceptors due to class loading issues. Should be fixed in next preview

**Closed** 2018-11-05 21:21 UTC
Labels: bug
