### ISSUE TITLE
Plugin throws exception when not in use

### ISSUE THREAD

**Issue by IvanMwiruki** [aws/aws-toolkit-jetbrains#510] opened 2018-11-16 22:26 UTC
**Describe the bug**
Been using my ide and haven't even touched the plugin but have encountered an exception from the plugin twice today. 

**To reproduce**
Not really any steps. Just use IntelliJ and don't use the plugin at all. 

**Expected behavior**
N/A

**Screenshots**
![plugin-exception](https://user-images.githubusercontent.com/13284085/48650431-eaee5480-e9aa-11e8-9e4e-58095f1f414d.png)

**Your Environment**
 - OS: macOS 10.13.6
 - JetBrains' Product: IntelliJ IDEA 2018.2.6 (Ultimate Edition)
 - JetBrains' Product Version: Build #IU-182.5107.16, built on November 6, 2018
 - Toolkit Version: beta

**Additional context**
Stacktrace:

```
java.lang.IllegalStateException: clz.containingFile.virtualFile must not be null
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.findByClass(JavaLambdaHandlerResolver.kt:131)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.access$findByClass(JavaLambdaHandlerResolver.kt:25)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:58)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:25)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:291)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandler(JavaLambdaHandlerResolver.kt:56)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:60)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:25)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:291)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandler(JavaLambdaHandlerResolver.kt:56)
	at software.aws.toolkits.jetbrains.services.lambda.upload.LambdaLineMarker.getLineMarkerInfo(LambdaLineMarker.kt:45)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:174)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by abrooksv** [comment] 2018-11-16 22:29
Out of curiosity, do you have anything like JSP files, or other files that have Java code embedded in them, but are not a .java file?

**Comment by IvanMwiruki** [comment] 2018-11-16 22:39
That's a good question. It doesn't look like I do.

**Comment by abrooksv** [comment] 2018-11-16 22:41
Duplicate of #494 

Going to close this as duplicate, we are working on short circuiting the logic if the virtual file is null

**Closed by abrooksv** 2018-11-16 22:41 UTC
Labels: bug
