### ISSUE TITLE
Plans for AWS step functions.

### ISSUE THREAD

**Issue by jvidin** [aws/aws-toolkit-jetbrains#1720] opened 2020-04-21 10:16 UTC
Any plans for AWS step functions in jetbrains toolkit ?
---
Toolkit: AWS Toolkit For JetBrains 1.13-201
OS: Windows 10 10.0
IDE: PyCharm Professional Edition 2020.1

**Comment by m-radzikowski** [comment] 2020-06-06 10:54
Duplicate of #584 ?

**Comment by abrooksv** [comment] 2020-06-08 19:43
Closing as duplicate of #584

**Closed by abrooksv** 2020-06-08 19:43 UTC
Labels: feature-request
