### ISSUE TITLE
CodeWhisperer: On disconnect(4 hours expiry), region isn't saved leading to "invalid grant"

### ISSUE THREAD

**Issue by colemvnio** [aws/aws-toolkit-jetbrains#3690] opened 2023-05-24 19:39 UTC
**Describe the bug**
When being disconnected after 4 hours(_annoying_), I attempt to reconnect by double clicking on "start", but it redirects me to another region's SSO other than the one I initially configured it for.

**To reproduce**
1. Login to CodeWhisperer, with SSO, in another region than "us-east-1"(default one)
2. Wait 4 hours to be logged out
3. Attempt to login
4. Look at the URL, it will be us-east-1 instead of your specified region

**Expected behavior**
To redirect on my proper SSO region initially configured.

**Screenshots**

**Your Environment**
- OS: Mac M1 Pro
- JetBrains product: Webstorm
- JetBrains product version: 2023.1
- AWS Toolkit version: 1.67-231
- SAM CLI version: N/A
- JVM/Python version: N/A

**Comment by rli** [comment] 2023-05-25 21:21
dupe of #3662

**Closed by rli** 2023-05-25 21:21 UTC
Labels: bug, codewhisperer
