### ISSUE TITLE
Pytest run config overridden by lambda run config when tests have two parameters

### ISSUE THREAD

**Issue by cfriedline** [aws/aws-toolkit-jetbrains#1011] opened 2019-06-06 17:34 UTC
**Describe the bug**
In an existing code base with lots of pytest tests, after installing the AWS toolkit, the run configurations for tests with two input parameters (i.e., fixtures) show up as lambdas and launch the lambda run config when clicking the play icon. However, tests which do not have two parameters do not have this problem.

![image](https://user-images.githubusercontent.com/3664445/59053033-730c4c80-885e-11e9-8ed9-c27b3f4334b7.png)

![image](https://user-images.githubusercontent.com/3664445/59053049-7acbf100-885e-11e9-9d55-a83edb9bf12f.png)

![image](https://user-images.githubusercontent.com/3664445/59053067-84555900-885e-11e9-9ed1-c5542c9670e1.png)

**To reproduce**
1. Open pytest file
2. Create a new test and fixtures
3. Attempt to run `test_anything()`, gets lambda popup
4. Attempt to run `test_anything2()`, runs pytest as expected

**Expected behavior**
In both cases, pytest should run the test and not cause the lambda run configuration dialog to come up

**Your Environment**
 - OS: MacOS 10.14.5
 - JetBrains' Product: PyCharm 
 - JetBrains' Product Version: 2019.1.3
 - Toolkit Version: 1.3 and 1.4-EAP.2019.05.29
 - SAM CLI Version: 0.16.1
 - JVM/Python Version: 3.7 in conda environment for the application code, sam installed `/usr/local/bin/python -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python` which is 2.7.16. This is the version that gets called by PyCharm, despite having sam installed in the project's conda environment.

**Comment by zhangzhx** [comment] 2019-06-08 00:20
Can you double check to see if you enabled the AWS setting `Show gutter icons for all potential AWS Lambda handlers`?

You can do this by **PyCharm** -> **Preferences** -> **Tools** -> **AWS** -> **Project settings**. For a workaround, you can turn off this check to avoid the Toolkit recognizing arbitrary suspicious functions.

**Comment by cfriedline** [comment] 2019-06-26 15:33
Thanks @zhangzhx. Indeed, I can turn off the gutter icons. However, even after I do that, when I click the play button on the test, even though it says "run pytest..." it still launches the dialog to run as if it were a lambda.

**Comment by abrooksv** [comment] 2019-06-27 17:27
That sounds super strange, we will need to dig into that discrepancy

**Comment by dylanjcastillo** [comment] 2019-11-08 10:03
Hey guys, I'm getting the same issue. Have you find any workaround for this?

**Comment by abrooksv** [comment] 2019-11-14 01:48
Here is the old youtrack issue that is the root cause: https://youtrack.jetbrains.com/issue/IDEA-135770

We do not have a workaround yet, we may have to put in some heuristic to disable it or something along those lines

**Comment by curtiscook** [comment] 2020-03-27 22:26
> Here is the old youtrack issue that is the root cause: https://youtrack.jetbrains.com/issue/IDEA-135770
> 
> We do not have a workaround yet, we may have to put in some heuristic to disable it or something along those lines
> 
> Edit: As in the youtrack, you can use Ctrl+Alt+R (on OS X) to work around it for now

Is there any update on this? It looks like the youtrack is 5 years old so it feels lost in the backlog. 

One thing to note, the UI looks like it wants to run pytest, but then Pycharm choses to try to generate an AWS Lambda

Ctrl-Alt-R sets up the configuration correctly and then you can use the play button after, but that's not really a sufficient workaround, since the issue is per test function and not per file

![Screen Shot 2020-03-27 at 3 19 09 PM](https://user-images.githubusercontent.com/7005517/77805197-94813380-703e-11ea-82be-a576ccb78d38.png)

**Comment by abrooksv** [comment] 2020-04-07 15:55
> > Here is the old youtrack issue that is the root cause: [youtrack.jetbrains.com/issue/IDEA-135770](https://youtrack.jetbrains.com/issue/IDEA-135770)
> > We do not have a workaround yet, we may have to put in some heuristic to disable it or something along those lines
> > Edit: As in the youtrack, you can use Ctrl+Alt+R (on OS X) to work around it for now
> 
> Is there any update on this? It looks like the youtrack is 5 years old so it feels lost in the backlog.
> 
> One thing to note, the UI looks like it wants to run pytest, but then Pycharm choses to try to generate an AWS Lambda
> 
> Ctrl-Alt-R sets up the configuration correctly and then you can use the play button after, but that's not a great workaround, since the issue is per test function and not per file
> 
> ![Screen Shot 2020-03-27 at 3 19 09 PM](https://user-images.githubusercontent.com/7005517/77805197-94813380-703e-11ea-82be-a576ccb78d38.png)
> 
> Edit: it seems the best workaround is to completely uninstall the AWS toolkit, which fixes the issue

Sorry for being quiet, this fell through the cracks and I apologize.

We are going to work around the IntelliJ bug and add checks in our logic:

1. Ignore any handlers that that are in a folder marked as a test root
2. Ignore any handlers that start with `test_` to avoid conflicting with pytest logic

**Closed** 2020-04-07 18:00 UTC
Labels: bug

**Comment by abrooksv** [comment] 2020-04-07 20:50
Change has been released in 1.12

**Comment by abrooksv** [comment] 2020-04-07 20:50
Please re-open if the issue is still showing up with v1.12

**Comment by curtiscook** [comment] 2020-04-07 20:51
awesome, thanks!
