### ISSUE TITLE
Rare SAM failure on Windows - PermissionError: [WinError 5] 

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#1823] opened 2020-06-04 23:41 UTC
SAM Build Rubymine 2019.3 fails on debug (it worked the first time): PermissionError: [WinError 5] Access is denied: 'C:\\Users\\<user>\\RubymineProjects\\untitled\\.aws-sam\\build\\HelloWorldFunction'

**Comment by DRSchlaubi** [comment] 2020-06-07 15:41
For me this happens every time after simulating a function call, the folder seems to be so extremely important, that windows does not give my permission to delete it, it makes sam-cli pretty much unusable since you have to wait about 2 minutes between builds

**Comment by DRSchlaubi** [comment] 2020-06-07 18:50
Turns out that the docker is somehow keeping access to the file. You can use process explorer to close the handle and it works again

**Comment by abrooksv** [comment] 2020-06-07 18:55
I was not able to reproduce this locally using the latest docker desktop version.

**Comment by saurabhajmera** [comment] 2023-05-04 21:24
Closing this since we haven't gotten a response. Please create a new issue with specific steps to reproduce the issue

**Closed by saurabhajmera** 2023-05-04 21:24 UTC
Labels: bug
