### ISSUE TITLE
PyCharm: Unable to debug AWS lambda

### ISSUE THREAD

**Issue by ro83rt** [aws/aws-toolkit-jetbrains#908] opened 2019-04-11 18:42 UTC
Since updating AWS Toolkit to 1.2 and Pycharm Community to 2019.1.1 I'm no longer able to debug any python lambda due to the:

pydev debugger: warning: trying to add breakpoint to file that does not exist

Find some advices to setup path mappings, but did not find such option AWS Lambda Run/Debug configurations.

Thank you for any help.

 - OS: Win 10 Pro
 - JetBrains' Product: PyCharm 
 - JetBrains' Product Version: 2019.1.1 (Community Edition)
 - Toolkit Version: 1.2
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: python3.6

**Comment by txf-alex** [comment] 2019-04-11 18:57
I have the same problem - running locally in Docker works fine, also starting local debug mode of the lambda works just fine, but breakpoints can't be set because the file mapping is off.

```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" local invoke --template C:\Users\sca\AppData\Local\Temp\lambdaBuild2\template.yaml --event "C:\Users\sca\AppData\Local\Temp\[Local] ManageIncomingEmails-event2.json" ManageIncomingEmails --debug-port 52760 --debugger-path "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev" --debug-args "-u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 52760 --file"
2019-04-11 20:52:11 Found credentials in environment variables.
2019-04-11 20:52:12 Invoking app.lambda_handler (python3.7)

Fetching lambci/lambda:python3.7 Docker container image......
2019-04-11 20:52:13 Mounting C:\Users\sca\AppData\Local\Temp\lambdaBuild2\ManageIncomingEmails as /var/task:ro inside runtime container
Connected to pydev debugger (build 191.6605.12)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /var/task/c:/data/qsync/projects/lambdatest010/email_receiver/app.py (will have no effect)
```
It looks like the full path of the source file is passed on to the debugger and not the relative path, so the debug process won't be able to map it to the correct file. The last line shows the strange path: mount point /var/task and then the full original path to the file on the host machine.

Other than that the code runs locally without problems.

- OS: Win 10 Pro
- JetBrains' Product: PyCharm
- JetBrains' Product Version: 2019.1.1 (Community Edition)
- Toolkit Version: v1.3-EAP.2019.04.11 
- SAM CLI Version: 0.14.2
- JVM/Python Version: python3.7

**Comment by praghavan039** [comment] 2019-04-12 07:28
I face the same issue. When can we expect the fix for this please.

**Comment by abrooksv** [comment] 2019-04-12 20:01
Built a Windows machine, and was able to reproduce it

**Comment by abrooksv** [comment] 2019-04-12 23:13
PyCharm lowercases all paths on Windows (https://github.com/JetBrains/intellij-community/blob/9d1d1a0b6e1661c14370e39e6c0d325879a615cc/python/src/com/jetbrains/python/debugger/PyLocalPositionConverter.java#L33) but our PathMapper is case sensitive.

**Comment by txf-alex** [comment] 2019-04-13 19:27
What I find odd though is that on a Windows machine Docker will mount the temp folder in %APPDATA%\Local\Temp\abc\def to /var/task, where a copy of the whole project folder has been placed.
But then it seems the debugger wants to access the original folder with an absolute path, hence /var/task/**c:/..** - which is a strange mapping.

Or is that exactly what the PathMapper is supposed to resolve and can't because of lowercase / mixed case mismatch?

**Comment by abrooksv** [comment] 2019-04-13 19:35
PathMapper maps the IDEs view of the world on to the Dockers view and back. This way it knows which file to put the break point in.

I have a fix I am testing

**Comment by imyhxy** [comment] 2019-04-18 07:52
How can I disable this `warning` for now, it just annoyed.

**Comment by 8848mzy** [comment] 2019-04-26 05:53
Same problem but on Mac OS since PyCharm change to sam build

**Comment by Rubyj** [comment] 2019-04-30 20:04
I have the same issue in aws toolkit 1.3 on linux

**Comment by Rubyj** [comment] 2019-04-30 20:05
@abrooksv I now have the same issue with the new aws toolkit 1.3 (wasn't happening before) on linux

**Comment by abrooksv** [comment] 2019-04-30 20:28
It should not have, since it was gated behind if your IDE is running on Windows.

We do test debugger does work in our integration tests on Linux, so not sure what is causing it to fail.

What is the actual path on your disk?

**Comment by Rubyj** [comment] 2019-04-30 20:34
@abrooksv Actually, the message there is the actual path on my disk. I'm confused as to why it "can't find the file". I definitely wasn't having this issue last week. Maybe a docker issue?

The absolute path is indeed `/home/rjacobs/git/s3-get-files-for-targetdb/s3-get-files-for-targetdb/build/app.py`

However I am not sure if that is correct for build/run time inside an image?

![image](https://user-images.githubusercontent.com/4855908/56991488-ce636480-6b65-11e9-911c-7ccf8791e649.png)

template.yml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    s3-get-files-for-targetdb

    Get predicition data and load into targetdb api


Resources:
    TargetBucket:
        Type: AWS::S3::Bucket
    s3GetForTagetDBFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: .
            Handler: s3-get-files-for-targetdb/build.app.lambda_handler
            Runtime: python3.7
            Timeout: 30
```

**Comment by abrooksv** [comment] 2019-04-30 20:37
It should map to `/var/task/s3-get-files-for-targetdb/build/app.py`.

Will attempt to reproduce it.

**Comment by Rubyj** [comment] 2019-04-30 20:39
Is it weird then that I am seeing 
```
pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/rjacobs/git/s3-get-files-for-targetdb/s3-get-files-for-targetdb/build/app.py (will have no effect)
```` 
and not a mention about `/var/task/s3-get-files-for-targetdb/build/app.py` then? 

Do I need to add the mapping manually to my interpreter? I am using venv not a remote interpreter. Ok thank you for your help.

**Comment by abrooksv** [comment] 2019-04-30 20:41
No, we handle the path mappings.

The path is supposed to be translated to the location inside the container, but it fails to map. When it fails to map, it is passed as is in, this is why you see the real path in the message.

**Comment by Rubyj** [comment] 2019-04-30 20:43
That makes sense. FYI I even tried reverting to a 1.3EAP version from last week (Thursday/Friday) when I know the issue was not happening and my breakpoints were being hit and yet I still am getting the same issue.

**Comment by abrooksv** [comment] 2019-04-30 20:44
We have logs, but they are at the debug level. Let me try to remember how to enable debug logs in IntelliJ.

**Comment by Rubyj** [comment] 2019-04-30 20:46
Sounds good. If it helps at all I am using PyCharm professional 2019.1.1 and the only things I have down was update my linux kernel (5.0), some packages on my system as part of a rolling system update, and updated the aws toolkit to 1.3 and then I started receiving this behavior.

**Comment by abrooksv** [comment] 2019-04-30 20:49
Go to Help->Debug Log Settings and add `software.aws.toolkits`. You may need to restart. You should then see a log line containing "Failed to map".

**Comment by Rubyj** [comment] 2019-04-30 20:56
```
2019-04-30 16:55:18,886 [  27993]  DEBUG - es.lambda.execution.PathMapper - Failed to map /home/rjacobs/git/s3-get-files-for-targetdb/s3-get-files-for-targetdb/build/app.py to remote file system: [PathMapping(localRoot='/home/rjacobs/git/s3-get-files-for-targetdb/./', remoteRoot='/var/task/'), PathMapping(localRoot='/tmp/lambdaBuild/s3GetForTagetDBFunction/', remoteRoot='/var/task/'), PathMapping(localRoot='/home/rjacobs/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/helpers/pydev/', remoteRoot='/tmp/lambci_debug_files/')] 
```

**Comment by abrooksv** [comment] 2019-04-30 21:00
If I had to guess, it is the /./ at the end of the first path.

**Comment by Rubyj** [comment] 2019-04-30 21:02
Ok thanks! If there is anything I can do please let me know.

**Comment by Rubyj** [comment] 2019-05-02 14:55
@abrooksv can confirm my issues are sorted. Built from source and tested. Great job!

**Closed** 2019-06-11 16:44 UTC
Labels: bug
