### ISSUE TITLE
Can't find python console debugger in pycharm

### ISSUE THREAD

**Issue by Spothedog1** [aws/aws-toolkit-jetbrains#1766] opened 2020-05-18 20:51 UTC
I can't find the button or anyway to bring up a Debug Console. Neither of the suggestions here work - https://www.jetbrains.com/help/pycharm/using-debug-console.html#

The python button isn't there and the tools option doesn't exist. I've attached a screen shot of what I'm seeing. I'm on PyCharm 2019.3

**To reproduce**
1. Set a breakpoint  
2. Run an AWS Lambda in Debug Mode
3. Look for missing python console

**Expected behavior**
There should be a [Python Button](https://www.jetbrains.com/help/pycharm/using-debug-console.html) in the debug console

**Screenshots**
![image](https://user-images.githubusercontent.com/7429961/82257698-7f31d280-9926-11ea-8f39-62d512cedbef.png)

**Your Environment**
- OS: macOS Catalina 10.15.4
- JetBrains product: PyCharm
- JetBrains product version: 2019.3.4
- AWS Toolkit version: 1.14-193
- SAM CLI version: 0.47.0
- JVM/Python version: 3.8

**Comment by abrooksv** [comment] 2020-05-18 20:57
It is not supported today. When I last delved into the PyCharm code to go looking for it, it was pretty buried and not able to get it to work without a larger refactor of all of our SAM run/debug support.

That work has not been prioritized yet.

This is a duplicate of https://github.com/aws/aws-toolkit-jetbrains/issues/1165, please +1 that feature request.

**Closed by abrooksv** 2020-05-18 20:57 UTC
Labels: bug
