### ISSUE TITLE
Run/Debug Lambda configuration > Input > Text -- no scrollbars causing large width dialog starting with 2023.2

### ISSUE THREAD

**Issue by genachka** [aws/aws-toolkit-jetbrains#3676] opened 2023-05-16 19:24 UTC
This started with IDEA 2023.1 and just updated to 2023.1.2 where it still happens. If I am working with Lambda function, on the Configuration tab of the Run/Debug configuration if I put an event template as text which may contain very long lines (i.e. some encrypted that has no word breaks) it used to have a horizontal and vertical scroll bar previously but now it makes the width of the dialog the same width as the text editor and it's impossible to see the left pane of other configurations, etc. and of course it's very difficult to work with event template contents this way too. And there's no way to reduce the width of the dialog unless the width of the text in the editor changes too but that can't if it's 1 long line. 

Can it either always have scrollbars or turn them on when needed as this would used to work fine previously?

Below is a screenshot of what's happening.
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/7947294/6ad72d12-da52-4734-900d-1db90738ba30)

**Comment by rli** [comment] 2023-05-16 19:54
dupe of #3657

**Closed by rli** 2023-05-16 19:54 UTC
Labels: bug
